/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.bomb.vacuum;

import project.bomb.vacuum.view.GUI;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        GUI.launchGUI();
    }
}
