/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.bomb.vacuum;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        GUI.launchGUI();
    }
}
